spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: db_user
    password: db_password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
